spring:
  application.name: survey
  datasource:
    url: jdbc:mariadb://${DATASOURCE_URL}/${DATASOURCE_PATH}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      uri: ${MONGO_PROTOCOL}://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_URL}/${MONGO_ADDITIONAL_DETAIL}
      database: ${DATASOURCE_PATH}
server:
  shutdown: graceful

app:
  jwt:
    secret: ${JWT_SECRET}
    access_expires_after: 86400000
    refresh_expires_after: 172800000
    issuer: jombi
